### ISSUE TITLE
Draco imported meshes doesn't Support secondary UV channel

### ISSUE THREAD

**Issue by prajwalshettydev** [atteneder/DracoUnity#11]
in v1.4.1, meshes with secondary uv channel are loaded with a single uv channel when imported using the draco extension. 
Draco compressed:
![image](https://user-images.githubusercontent.com/18365548/112046532-2ea48a80-8b72-11eb-9fa6-e35886771212.png) 

Normal version of the same glb:
![image](https://user-images.githubusercontent.com/18365548/112046680-58f64800-8b72-11eb-91ae-eacd2294d37d.png)

I went through the source as well, as it seems the `class PrimitiveCreateContext` has the textcoord apply to mesh related functions, where as in case of a draco mesh `class PrimitiveDracoCreateContext` is using `DracoMeshLoader.CreateMesh` function to setup the mesh. 

If you could at least show me a direction on where I could add the temporary uv2 support(if currently not supported for draco meshes using gltffast) that would also be of great help. Also thanks for all the amazing plugins.

**Comment by prajwalshettydev** [comment]
If in case you need the sample Draco compressed GLB that I have shown in the above screenshot: 
[Coffee tableDracoButCombined.zip](https://github.com/atteneder/DracoUnity/files/6184847/Coffee.tableDracoButCombined.zip)

**Comment by atteneder** [comment]
Hi @prajwalshettydev ,

Thanks for reporting the issue!

I'd prefer to not fix this in 1.4.x anymore. Development on version 2.0.0-preview of DracoUnity is only having one remainging problem with weights/joints. It is a refactor with multiple UVs in mind (but not tested).

Feel free to test your model with the newer version. I've just pushed the [corresponding glTFast branch,](https://github.com/atteneder/glTFast/tree/draco2) that works with DracoUnity 2.x.

hth

**Comment by prajwal-spacejoy** [comment]
I gave this a try in 2.x, it didn't resolve my issue, It also threw a few exceptions, so I'm assuming these errors could be the reason behind it. 
![image](https://user-images.githubusercontent.com/75058932/114741240-3073ff00-9d68-11eb-9ff6-c8513e37fe10.png)
